version: "3.8"

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  go-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-worker
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    command: ["./app", "-mode=worker", "-redis=redis:6379"]
    restart: always

  go-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-client
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    command: ["./app", "-mode=client", "-redis=redis:6379"]
    restart: always

  asynqmon:
    image: hibiken/asynqmon
    container_name: asynqmon
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

volumes:
  redis-data:
